import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import AdminSidebar from "@/components/admin/AdminSidebar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Admin Dashboard",
    description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased relative grid gap-7 grid-cols-[250px_1fr]`}
            >
                <AdminSidebar />
                {children}
            </body>
        </html>
    );
}
